## Burenkov Valentyn


In [1]:
import torch

### 1. Створіть випадковий тензор форми `(7, 7)`.


In [2]:
# Create random tensor
t1 = torch.rand(7,7)
print(t1)

tensor([[0.5185, 0.7702, 0.3009, 0.3793, 0.3434, 0.5129, 0.6544],
        [0.3925, 0.3516, 0.2414, 0.4413, 0.0100, 0.8518, 0.4970],
        [0.3982, 0.9817, 0.3497, 0.6472, 0.7837, 0.0745, 0.6524],
        [0.9420, 0.4786, 0.4251, 0.5582, 0.7705, 0.4600, 0.7144],
        [0.6750, 0.5319, 0.8053, 0.3003, 0.7012, 0.8970, 0.4646],
        [0.0782, 0.7652, 0.4216, 0.9162, 0.7357, 0.8553, 0.5260],
        [0.4337, 0.0635, 0.0190, 0.6049, 0.8720, 0.4954, 0.9008]])


### 2. Виконайте матричне множенні для тензора з 1 завдання і випадкового тензора форми `(1, 7)` (за необхідності, транспонуйте другий тензор).

In [3]:
# Create another random tensor
t2 = torch.rand(1, 7)
# Perform matrix multiplication 
res = t1 @ t2.T
print(res)
print(res.shape)

tensor([[1.4165],
        [1.3809],
        [1.4953],
        [1.7162],
        [1.6391],
        [2.0350],
        [1.7456]])
torch.Size([7, 1])


### 3. Встановіть random seed в `0` і виконайте завдання 1 і 2 знову.

In [11]:
# Set manual seed
torch.manual_seed(43)

# Create two random tensors
t1 = torch.rand(7,7)
t2 = torch.rand(1, 7)

# Matrix multiply tensors
res = t1 @ t2.T
print(res)

tensor([[1.6682],
        [1.6954],
        [2.0499],
        [2.7727],
        [2.8330],
        [1.7068],
        [1.7485]])


### 4. Знайдіть максимальне і мінімальне значення у виході 3 завдання.

In [20]:
# Find max
print(res.max())
# Find min
print(res.min())

tensor(2.8330)
tensor(1.6682)


In [21]:
device = "cuda" if torch.cuda.is_available() else "cpu"
res.to(device)

tensor([[1.6682],
        [1.6954],
        [2.0499],
        [2.7727],
        [2.8330],
        [1.7068],
        [1.7485]], device='cuda:0')

### 5. Знайдіть індекси максимального і мінімального значення у виході 3 завдання.

In [25]:
# Find arg max
print('Max index: {0}'.format(res.argmax()))

# Find arg min
print('Min index: {0}'.format(res.argmin()))

Max index: 4
Min index: 0



### 6. Створіть випадковий тензор форми `(1, 1, 1, 10)`. Потім з нього створіть новий тензор, у якого вилучено всі одиничні розмірності. При створенні тензору встановіть seed рівним `7`. Надрукуйте перший і другий тензори і їхню форму.

In [33]:
# Set seed
torch.manual_seed(111)

# Create random tensor
t1 = torch.rand(size=(1,1,1,10))

# Remove single dimensions
r1_squeezed = t1.squeeze()

# Print out tensors and their shapes
print(t1.shape)
print(r1_squeezed.shape)

torch.Size([1, 1, 1, 10])
torch.Size([10])
