In [ ]:
import torch
torch.__version__

In [2]:
t = torch.tensor(7)

In [3]:
t = torch.tensor([[1,4], [5, 5]])

In [4]:
t.shape

torch.Size([2, 2])

In [5]:
t = torch.tensor([[4,5,1],[6, 5, 11]])

In [6]:
t = torch.tensor( [[[1, 4, 5], [5, 32, 4], [6,4,1]]] )

In [7]:
t.ndim

3

In [8]:
t.shape

torch.Size([1, 3, 3])

In [9]:
print(t)

tensor([[[ 1,  4,  5],
         [ 5, 32,  4],
         [ 6,  4,  1]]])


In [10]:
t + 10

tensor([[[11, 14, 15],
         [15, 42, 14],
         [16, 14, 11]]])

In [11]:
t - 11

tensor([[[-10,  -7,  -6],
         [ -6,  21,  -7],
         [ -5,  -7, -10]]])

In [12]:
t * 10

tensor([[[ 10,  40,  50],
         [ 50, 320,  40],
         [ 60,  40,  10]]])

In [13]:
torch.multiply(t, 10)

tensor([[[ 10,  40,  50],
         [ 50, 320,  40],
         [ 60,  40,  10]]])

In [14]:
e1 = torch.tensor([[1, 3, 5], [6, 5, 1]])

In [15]:
e2 = torch.tensor([[1, 5], [6, 12], [8, 9]])

In [16]:
torch.matmul(e1, e2)

tensor([[59, 86],
        [44, 99]])

In [17]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2,  # in_features = matches inner dimension of input 
                         out_features=6) # out_features = describes outer value 
x = torch.tensor([[1, 2],
                  [3, 4],
                  [5, 6]], dtype=torch.float32)
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


In [18]:
linear

Linear(in_features=2, out_features=6, bias=True)

In [19]:
t = torch.arange(0, 100, 5)

In [20]:
t.dtype

torch.int64

In [21]:
t.type(torch.float32).mean()

tensor(47.5000)

In [22]:
print(t)

tensor([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
        90, 95])


In [23]:
t.shape

torch.Size([20])

In [24]:
tR = t.reshape(4,5)

In [25]:
tV = tR.view(2, 10)

In [26]:
tR[:, 0] = 111

In [27]:
tR[1, 4] = 115

In [28]:
tR

tensor([[111,   5,  10,  15,  20],
        [111,  30,  35,  40, 115],
        [111,  55,  60,  65,  70],
        [111,  80,  85,  90,  95]])

In [29]:
tR.squeeze()

tensor([[111,   5,  10,  15,  20],
        [111,  30,  35,  40, 115],
        [111,  55,  60,  65,  70],
        [111,  80,  85,  90,  95]])

In [30]:
x = torch.tensor([1, 4, 89, 15])

In [31]:
print(x)

tensor([ 1,  4, 89, 15])


In [32]:
torch.stack([x,x,x,x], dim=0)

tensor([[ 1,  4, 89, 15],
        [ 1,  4, 89, 15],
        [ 1,  4, 89, 15],
        [ 1,  4, 89, 15]])

In [33]:
torch.stack([x,x,x,x], dim=1)

tensor([[ 1,  1,  1,  1],
        [ 4,  4,  4,  4],
        [89, 89, 89, 89],
        [15, 15, 15, 15]])

In [34]:
!nvidia-smi

Sun May  7 17:22:13 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 531.79                 Driver Version: 531.79       CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                      TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce 940MX          WDDM | 00000000:01:00.0 Off |                  N/A |
| N/A    0C    P8               N/A /  N/A|      0MiB /  4096MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [35]:
torch.cuda.is_available()

False